export const currenciesList = [
    { label: 'EUR, €', value: 'EUR', symbol: '€' },
    { label: 'USD, $', value: 'USD', symbol: '$' },
    { label: 'AUD, $', value: 'AUD', symbol: '$' },
    { label: 'CAD, $', value: 'CAD', symbol: '$' },
    { label: 'CHF, CHF', value: 'CHF', symbol: 'CHF' },
    { label: 'CNY, ¥', value: 'CNY', symbol: '¥' },
    { label: 'CZK, Kč', value: 'CZK', symbol: 'Kč' },
    { label: 'DKK, Kr.', value: 'DKK', symbol: 'Kr.' },
    { label: 'GBP, £', value: 'GBP', symbol: '£' },
    { label: 'HKD, $', value: 'HKD', symbol: '$' },
    { label: 'HUF, Ft', value: 'HUF', symbol: 'Ft' },
    { label: 'ILS, ₪', value: 'ILS', symbol: '₪' },
    { label: 'INR, ₹', value: 'INR', symbol: '₹' },
    { label: 'JPY, ¥', value: 'JPY', symbol: '¥' },
    { label: 'KRW, ₩', value: 'KRW', symbol: '₩' },
    { label: 'MXN, $', value: 'MXN', symbol: '$' },
    { label: 'NOK, kr', value: 'NOK', symbol: 'kr' },
    { label: 'NZD, $', value: 'NZD', symbol: '$' },
    { label: 'PHP, ₱', value: 'PHP', symbol: '₱' },
    { label: 'PLN, zł', value: 'PLN', symbol: 'zł' },
    { label: 'RUB, руб.', value: 'RUB', symbol: 'руб.' },
    { label: 'SEK, kr', value: 'SEK', symbol: 'kr' },
    { label: 'SGD, $', value: 'SGD', symbol: '$' },
    { label: 'THB, ฿', value: 'THB', symbol: '฿' },
  ]
  