// List of countries using dot as decimal separator for currencies
export const countriesUsingDecimal = [
    'Australia',
    'Bangladesh',
    'Botswana',
    'British West Indies',
    'Brunei',
    'Cambodia',
    'Canada',
    'China',
    'Cyprus',
    'Dominican Republic',
    'Egypt',
    'El Salvador',
    'Ethiopia',
    'Ghana',
    'Guatemala',
    'Honduras',
    'Hong Kong',
    'India',
    'Ireland',
    'Israel',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kenya',
    'Korea',
    'Libya',
    'Liechtenstein',
    'Luxembourg',
    'Lebanon',
    'Malaysia',
    'Maldives',
    'Malta',
    'Mexico',
    'Myanmar',
    'Namibia',
    'Nepal',
    'New Zealand',
    'Nicaragua',
    'Nigeria',
    'Pakistan',
    'Panama',
    'Philippines',
    'Puerto Rico',
    'Qatar',
    'Saudi Arabia',
    'Singapore',
    'Somalia',
    'Sri Lanka',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Uganda',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Zimbabwe',
  ]
  