export const languagesData = [
  { label: 'Afrikaans', value: 'Afrikaans' },
  { label: 'عربى', value: 'Arab' },
  { label: 'Bangla', value: 'Bangla' },
  { label: 'Basa Jawa', value: 'Basa Jawa' },
  { label: 'Bosnian', value: 'Bosnian' },
  { label: 'Bulgarian', value: 'Bulgarian' },
  { label: 'Catalan', value: 'Catalan' },
  { label: 'Chechen', value: 'Chechen' },
  { label: 'Chinese', value: 'Chinese' },
  { label: 'Croatian', value: 'Croatian' },
  { label: 'Czech', value: 'Czech' },
  { label: 'Danish', value: 'Danish' },
  { label: 'Deutsch', value: 'Deutsch' },
  { label: 'Dutch', value: 'Dutch' },
  { label: 'English', value: 'English' },
  { label: 'Espanol', value: 'Espanol' },
  { label: 'Filipino', value: 'Filipino' },
  { label: 'Finnish', value: 'Finnish' },
  { label: 'French', value: 'French' },
  { label: 'German', value: 'German' },
  { label: 'Greek', value: 'Greek' },
  { label: 'Harshen Hausa', value: 'Harshen Hausa' },
  { label: 'עִברִית', value: 'Hebrew' },
  { label: 'Hindi', value: 'Hindi' },
  { label: 'Hungarian', value: 'Hungarian' },
  { label: 'Indonesian', value: 'Indonesian' },
  { label: 'Italian', value: 'Italian' },
  { label: '日本語', value: 'Japnese' },
  { label: '한국어', value: 'Korean' },
  { label: 'Malay', value: 'Malay' },
  { label: 'Norwegian', value: 'Norwegian' },
  { label: 'Polish', value: 'Polish' },
  { label: 'Portuguese', value: 'Portugues' },
  { label: 'Punjabi', value: 'Punjabi' },
  { label: 'Romanian', value: 'Romanian' },
  { label: 'русский', value: 'Russian' },
  { label: 'Serbian', value: 'Serbian' },
  { label: 'Slovak', value: 'Slovak' },
  { label: 'Slovenian', value: 'Slovenian' },
  { label: 'Somali', value: 'Somali' },
  { label: 'Spanish', value: 'Spanish' },
  { label: 'Swedish', value: 'Swedish' },
  { label: 'Tamil', value: 'Tamil' },
  { label: 'ไทย', value: 'Thai' },
  { label: 'Turkish', value: 'Turkish' },
  { label: 'Ukrainian', value: 'Ukrainian' },
  { label: 'Vietnamese', value: 'Vietnam' },
  { label: 'Other [not listed yet]', value: 'others' }
  ]



