export const Africa = [
    { value: 'Africa/Abidjan', label: 'Abidjan', className: 'left-pad' },
    { value: 'Africa/Accra', label: 'Accra', className: 'left-pad' },
    { value: 'Africa/Addis_Ababa', label: 'Addis Ababa', className: 'left-pad' },
    { value: 'Africa/Algiers', label: 'Algiers', className: 'left-pad' },
    { value: 'Africa/Asmara', label: 'Asmara', className: 'left-pad' },
    { value: 'Africa/Bamako', label: 'Bamako', className: 'left-pad' },
    { value: 'Africa/Bangui', label: 'Bangui', className: 'left-pad' },
    { value: 'Africa/Banjul', label: 'Banjul', className: 'left-pad' },
    { value: 'Africa/Bissau', label: 'Bissau', className: 'left-pad' },
    { value: 'Africa/Blantyre', label: 'Blantyre', className: 'left-pad' },
    { value: 'Africa/Brazzaville', label: 'Brazzaville', className: 'left-pad' },
    { value: 'Africa/Bujumbura', label: 'Bujumbura', className: 'left-pad' },
    { value: 'Africa/Cairo', label: 'Cairo', className: 'left-pad' },
    { value: 'Africa/Casablanca', label: 'Casablanca', className: 'left-pad' },
    { value: 'Africa/Ceuta', label: 'Ceuta', className: 'left-pad' },
    { value: 'Africa/Conakry', label: 'Conakry', className: 'left-pad' },
    { value: 'Africa/Dakar', label: 'Dakar', className: 'left-pad' },
    { value: 'Africa/Dar_es_Salaam', label: 'Dar es Salaam', className: 'left-pad' },
    { value: 'Africa/Djibouti', label: 'Djibouti', className: 'left-pad' },
    { value: 'Africa/Douala', label: 'Douala', className: 'left-pad' },
    { value: 'Africa/El_Aaiun', label: 'El Aaiun', className: 'left-pad' },
    { value: 'Africa/Freetown', label: 'Freetown', className: 'left-pad' },
    { value: 'Africa/Gaborone', label: 'Gaborone', className: 'left-pad' },
    { value: 'Africa/Harare', label: 'Harare', className: 'left-pad' },
    { value: 'Africa/Johannesburg', label: 'Johannesburg', className: 'left-pad' },
    { value: 'Africa/Juba', label: 'Juba', className: 'left-pad' },
    { value: 'Africa/Kampala', label: 'Kampala', className: 'left-pad' },
    { value: 'Africa/Khartoum', label: 'Khartoum', className: 'left-pad' },
    { value: 'Africa/Kigali', label: 'Kigali', className: 'left-pad' },
    { value: 'Africa/Kinshasa', label: 'Kinshasa', className: 'left-pad' },
    { value: 'Africa/Lagos', label: 'Lagos', className: 'left-pad' },
    { value: 'Africa/Libreville', label: 'Libreville', className: 'left-pad' },
    { value: 'Africa/Lome', label: 'Lome', className: 'left-pad' },
    { value: 'Africa/Luanda', label: 'Luanda', className: 'left-pad' },
    { value: 'Africa/Lubumbashi', label: 'Lubumbashi', className: 'left-pad' },
    { value: 'Africa/Lusaka', label: 'Lusaka', className: 'left-pad' },
    { value: 'Africa/Malabo', label: 'Malabo', className: 'left-pad' },
    { value: 'Africa/Maputo', label: 'Maputo', className: 'left-pad' },
    { value: 'Africa/Maseru', label: 'Maseru', className: 'left-pad' },
    { value: 'Africa/Mbabane', label: 'Mbabane', className: 'left-pad' },
    { value: 'Africa/Mogadishu', label: 'Mogadishu', className: 'left-pad' },
    { value: 'Africa/Monrovia', label: 'Monrovia', className: 'left-pad' },
    { value: 'Africa/Nairobi', label: 'Nairobi', className: 'left-pad' },
    { value: 'Africa/Ndjamena', label: 'Ndjamena', className: 'left-pad' },
    { value: 'Africa/Niamey', label: 'Niamey', className: 'left-pad' },
    { value: 'Africa/Nouakchott', label: 'Nouakchott', className: 'left-pad' },
    { value: 'Africa/Ouagadougou', label: 'Ouagadougou', className: 'left-pad' },
    { value: 'Africa/Porto-Novo', label: 'Porto-Novo', className: 'left-pad' },
    { value: 'Africa/Sao_Tome', label: 'Sao Tome', className: 'left-pad' },
    { value: 'Africa/Tripoli', label: 'Tripoli', className: 'left-pad' },
    { value: 'Africa/Tunis', label: 'Tunis', className: 'left-pad' },
    { value: 'Africa/Windhoek', label: 'Windhoek', className: 'left-pad' },
  ]
  export const America = [
    { value: 'America/Adak', label: 'Adak', className: 'left-pad' },
    { value: 'America/Anchorage', label: 'Anchorage', className: 'left-pad' },
    { value: 'America/Anguilla', label: 'Anguilla', className: 'left-pad' },
    { value: 'America/Antigua', label: 'Antigua', className: 'left-pad' },
    { value: 'America/Araguaina', label: 'Araguaina', className: 'left-pad' },
    { value: 'America/Argentina/Buenos_Aires', label: 'Argentina - Buenos Aires', className: 'left-pad' },
    { value: 'America/Argentina/Catamarca', label: 'Argentina - Catamarca', className: 'left-pad' },
    { value: 'America/Argentina/Cordoba', label: 'Argentina - Cordoba', className: 'left-pad' },
    { value: 'America/Argentina/Jujuy', label: 'Argentina - Jujuy', className: 'left-pad' },
    { value: 'America/Argentina/La_Rioja', label: 'Argentina - La Rioja', className: 'left-pad' },
    { value: 'America/Argentina/Mendoza', label: 'Argentina - Mendoza', className: 'left-pad' },
    { value: 'America/Argentina/Rio_Gallegos', label: 'Argentina - Rio Gallegos', className: 'left-pad' },
    { value: 'America/Argentina/Salta', label: 'Argentina - Salta', className: 'left-pad' },
    { value: 'America/Argentina/San_Juan', label: 'Argentina - San Juan', className: 'left-pad' },
    { value: 'America/Argentina/San_Luis', label: 'Argentina - San Luis', className: 'left-pad' },
    { value: 'America/Argentina/Tucuman', label: 'Argentina - Tucuman', className: 'left-pad' },
    { value: 'America/Argentina/Ushuaia', label: 'Argentina - Ushuaia', className: 'left-pad' },
    { value: 'America/Aruba', label: 'Aruba', className: 'left-pad' },
    { value: 'America/Asuncion', label: 'Asuncion', className: 'left-pad' },
    { value: 'America/Atikokan', label: 'Atikokan', className: 'left-pad' },
    { value: 'America/Bahia', label: 'Bahia', className: 'left-pad' },
    { value: 'America/Bahia_Banderas', label: 'Bahia Banderas', className: 'left-pad' },
    { value: 'America/Barbados', label: 'Barbados', className: 'left-pad' },
    { value: 'America/Belem', label: 'Belem', className: 'left-pad' },
    { value: 'America/Belize', label: 'Belize', className: 'left-pad' },
    { value: 'America/Blanc-Sablon', label: 'Blanc-Sablon', className: 'left-pad' },
    { value: 'America/Boa_Vista', label: 'Boa Vista', className: 'left-pad' },
    { value: 'America/Bogota', label: 'Bogota', className: 'left-pad' },
    { value: 'America/Boise', label: 'Boise', className: 'left-pad' },
    { value: 'America/Cambridge_Bay', label: 'Cambridge Bay', className: 'left-pad' },
    { value: 'America/Campo_Grande', label: 'Campo Grande', className: 'left-pad' },
    { value: 'America/Cancun', label: 'Cancun', className: 'left-pad' },
    { value: 'America/Caracas', label: 'Caracas', className: 'left-pad' },
    { value: 'America/Cayenne', label: 'Cayenne', className: 'left-pad' },
    { value: 'America/Cayman', label: 'Cayman', className: 'left-pad' },
    { value: 'America/Chicago', label: 'Chicago', className: 'left-pad' },
    { value: 'America/Chihuahua', label: 'Chihuahua', className: 'left-pad' },
    { value: 'America/Costa_Rica', label: 'Costa Rica', className: 'left-pad' },
    { value: 'America/Creston', label: 'Creston', className: 'left-pad' },
    { value: 'America/Cuiaba', label: 'Cuiaba', className: 'left-pad' },
    { value: 'America/Curacao', label: 'Curacao', className: 'left-pad' },
    { value: 'America/Danmarkshavn', label: 'Danmarkshavn', className: 'left-pad' },
    { value: 'America/Dawson', label: 'Dawson', className: 'left-pad' },
    { value: 'America/Dawson_Creek', label: 'Dawson Creek', className: 'left-pad' },
    { value: 'America/Denver', label: 'Denver', className: 'left-pad' },
    { value: 'America/Detroit', label: 'Detroit', className: 'left-pad' },
    { value: 'America/Dominica', label: 'Dominica', className: 'left-pad' },
    { value: 'America/Edmonton', label: 'Edmonton', className: 'left-pad' },
    { value: 'America/Eirunepe', label: 'Eirunepe', className: 'left-pad' },
    { value: 'America/El_Salvador', label: 'El Salvador', className: 'left-pad' },
    { value: 'America/Fortaleza', label: 'Fortaleza', className: 'left-pad' },
    { value: 'America/Fort_Nelson', label: 'Fort Nelson', className: 'left-pad' },
    { value: 'America/Glace_Bay', label: 'Glace Bay', className: 'left-pad' },
    { value: 'America/Goose_Bay', label: 'Goose Bay', className: 'left-pad' },
    { value: 'America/Grand_Turk', label: 'Grand Turk', className: 'left-pad' },
    { value: 'America/Grenada', label: 'Grenada', className: 'left-pad' },
    { value: 'America/Guadeloupe', label: 'Guadeloupe', className: 'left-pad' },
    { value: 'America/Guatemala', label: 'Guatemala', className: 'left-pad' },
    { value: 'America/Guayaquil', label: 'Guayaquil', className: 'left-pad' },
    { value: 'America/Guyana', label: 'Guyana', className: 'left-pad' },
    { value: 'America/Halifax', label: 'Halifax', className: 'left-pad' },
    { value: 'America/Havana', label: 'Havana', className: 'left-pad' },
    { value: 'America/Hermosillo', label: 'Hermosillo', className: 'left-pad' },
    { value: 'America/Indiana/Indianapolis', label: 'Indiana - Indianapolis', className: 'left-pad' },
    { value: 'America/Indiana/Knox', label: 'Indiana - Knox', className: 'left-pad' },
    { value: 'America/Indiana/Marengo', label: 'Indiana - Marengo', className: 'left-pad' },
    { value: 'America/Indiana/Petersburg', label: 'Indiana - Petersburg', className: 'left-pad' },
    { value: 'America/Indiana/Tell_City', label: 'Indiana - Tell City', className: 'left-pad' },
    { value: 'America/Indiana/Vevay', label: 'Indiana - Vevay', className: 'left-pad' },
    { value: 'America/Indiana/Vincennes', label: 'Indiana - Vincennes', className: 'left-pad' },
    { value: 'America/Indiana/Winamac', label: 'Indiana - Winamac', className: 'left-pad' },
    { value: 'America/Inuvik', label: 'Inuvik', className: 'left-pad' },
    { value: 'America/Iqaluit', label: 'Iqaluit', className: 'left-pad' },
    { value: 'America/Jamaica', label: 'Jamaica', className: 'left-pad' },
    { value: 'America/Juneau', label: 'Juneau', className: 'left-pad' },
    { value: 'America/Kentucky/Louisville', label: 'Kentucky - Louisville', className: 'left-pad' },
    { value: 'America/Kentucky/Monticello', label: 'Kentucky - Monticello', className: 'left-pad' },
    { value: 'America/Kralendijk', label: 'Kralendijk', className: 'left-pad' },
    { value: 'America/La_Paz', label: 'La Paz', className: 'left-pad' },
    { value: 'America/Lima', label: 'Lima', className: 'left-pad' },
    { value: 'America/Los_Angeles', label: 'Los Angeles', className: 'left-pad' },
    { value: 'America/Lower_Princes', label: 'Lower Princes', className: 'left-pad' },
    { value: 'America/Maceio', label: 'Maceio', className: 'left-pad' },
    { value: 'America/Managua', label: 'Managua', className: 'left-pad' },
    { value: 'America/Manaus', label: 'Manaus', className: 'left-pad' },
    { value: 'America/Marigot', label: 'Marigot', className: 'left-pad' },
    { value: 'America/Martinique', label: 'Martinique', className: 'left-pad' },
    { value: 'America/Matamoros', label: 'Matamoros', className: 'left-pad' },
    { value: 'America/Mazatlan', label: 'Mazatlan', className: 'left-pad' },
    { value: 'America/Menominee', label: 'Menominee', className: 'left-pad' },
    { value: 'America/Merida', label: 'Merida', className: 'left-pad' },
    { value: 'America/Metlakatla', label: 'Metlakatla', className: 'left-pad' },
    { value: 'America/Mexico_City', label: 'Mexico City', className: 'left-pad' },
    { value: 'America/Miquelon', label: 'Miquelon', className: 'left-pad' },
    { value: 'America/Moncton', label: 'Moncton', className: 'left-pad' },
    { value: 'America/Monterrey', label: 'Monterrey', className: 'left-pad' },
    { value: 'America/Montevideo', label: 'Montevideo', className: 'left-pad' },
    { value: 'America/Montserrat', label: 'Montserrat', className: 'left-pad' },
    { value: 'America/Nassau', label: 'Nassau', className: 'left-pad' },
    { value: 'America/New_York', label: 'New York', className: 'left-pad' },
    { value: 'America/Nipigon', label: 'Nipigon', className: 'left-pad' },
    { value: 'America/Nome', label: 'Nome', className: 'left-pad' },
    { value: 'America/Noronha', label: 'Noronha', className: 'left-pad' },
    { value: 'America/North_Dakota/Beulah', label: 'North Dakota - Beulah', className: 'left-pad' },
    { value: 'America/North_Dakota/Center', label: 'North Dakota - Center', className: 'left-pad' },
    { value: 'America/North_Dakota/New_Salem', label: 'North Dakota - New Salem', className: 'left-pad' },
    { value: 'America/Nuuk', label: 'Nuuk', className: 'left-pad' },
    { value: 'America/Ojinaga', label: 'Ojinaga', className: 'left-pad' },
    { value: 'America/Panama', label: 'Panama', className: 'left-pad' },
    { value: 'America/Pangnirtung', label: 'Pangnirtung', className: 'left-pad' },
    { value: 'America/Paramaribo', label: 'Paramaribo', className: 'left-pad' },
    { value: 'America/Phoenix', label: 'Phoenix', className: 'left-pad' },
    { value: 'America/Port-au-Prince', label: 'Port-au-Prince', className: 'left-pad' },
    { value: 'America/Port_of_Spain', label: 'Port of Spain', className: 'left-pad' },
    { value: 'America/Porto_Velho', label: 'Porto Velho', className: 'left-pad' },
    { value: 'America/Puerto_Rico', label: 'Puerto Rico', className: 'left-pad' },
    { value: 'America/Punta_Arenas', label: 'Punta Arenas', className: 'left-pad' },
    { value: 'America/Rainy_River', label: 'Rainy River', className: 'left-pad' },
    { value: 'America/Rankin_Inlet', label: 'Rankin Inlet', className: 'left-pad' },
    { value: 'America/Recife', label: 'Recife', className: 'left-pad' },
    { value: 'America/Regina', label: 'Regina', className: 'left-pad' },
    { value: 'America/Resolute', label: 'Resolute', className: 'left-pad' },
    { value: 'America/Rio_Branco', label: 'Rio Branco', className: 'left-pad' },
    { value: 'America/Santarem', label: 'Santarem', className: 'left-pad' },
    { value: 'America/Santiago', label: 'Santiago', className: 'left-pad' },
    { value: 'America/Santo_Domingo', label: 'Santo Domingo', className: 'left-pad' },
    { value: 'America/Sao_Paulo', label: 'Sao Paulo', className: 'left-pad' },
    { value: 'America/Scoresbysund', label: 'Scoresbysund', className: 'left-pad' },
    { value: 'America/Sitka', label: 'Sitka', className: 'left-pad' },
    { value: 'America/St_Barthelemy', label: 'St Barthelemy', className: 'left-pad' },
    { value: 'America/St_Johns', label: 'St Johns', className: 'left-pad' },
    { value: 'America/St_Kitts', label: 'St Kitts', className: 'left-pad' },
    { value: 'America/St_Lucia', label: 'St Lucia', className: 'left-pad' },
    { value: 'America/St_Thomas', label: 'St Thomas', className: 'left-pad' },
    { value: 'America/St_Vincent', label: 'St Vincent', className: 'left-pad' },
    { value: 'America/Swift_Current', label: 'Swift Current', className: 'left-pad' },
    { value: 'America/Tegucigalpa', label: 'Tegucigalpa', className: 'left-pad' },
    { value: 'America/Thule', label: 'Thule', className: 'left-pad' },
    { value: 'America/Thunder_Bay', label: 'Thunder Bay', className: 'left-pad' },
    { value: 'America/Tijuana', label: 'Tijuana', className: 'left-pad' },
    { value: 'America/Toronto', label: 'Toronto', className: 'left-pad' },
    { value: 'America/Tortola', label: 'Tortola', className: 'left-pad' },
    { value: 'America/Vancouver', label: 'Vancouver', className: 'left-pad' },
    { value: 'America/Whitehorse', label: 'Whitehorse', className: 'left-pad' },
    { value: 'America/Winnipeg', label: 'Winnipeg', className: 'left-pad' },
    { value: 'America/Yakutat', label: 'Yakutat', className: 'left-pad' },
    { value: 'America/Yellowknife', label: 'Yellowknife', className: 'left-pad' },
  ]
  export const Antarctica = [
    { value: 'Antarctica/Casey', label: 'Casey', className: 'left-pad' },
    { value: 'Antarctica/Davis', label: 'Davis', className: 'left-pad' },
    { value: 'Antarctica/DumontDUrville', label: 'DumontDUrville', className: 'left-pad' },
    { value: 'Antarctica/Macquarie', label: 'Macquarie', className: 'left-pad' },
    { value: 'Antarctica/Mawson', label: 'Mawson', className: 'left-pad' },
    { value: 'Antarctica/McMurdo', label: 'McMurdo', className: 'left-pad' },
    { value: 'Antarctica/Palmer', label: 'Palmer', className: 'left-pad' },
    { value: 'Antarctica/Rothera', label: 'Rothera', className: 'left-pad' },
    { value: 'Antarctica/Syowa', label: 'Syowa', className: 'left-pad' },
    { value: 'Antarctica/Troll', label: 'Troll', className: 'left-pad' },
    { value: 'Antarctica/Vostok', label: 'Vostok', className: 'left-pad' },
  ]
  export const Arctic = [{ value: 'Arctic/Longyearbyen', label: 'Longyearbyen' }]
  export const Asia = [
    { value: 'Asia/Aden', label: 'Aden', className: 'left-pad' },
    { value: 'Asia/Almaty', label: 'Almaty', className: 'left-pad' },
    { value: 'Asia/Amman', label: 'Amman', className: 'left-pad' },
    { value: 'Asia/Anadyr', label: 'Anadyr', className: 'left-pad' },
    { value: 'Asia/Aqtau', label: 'Aqtau', className: 'left-pad' },
    { value: 'Asia/Aqtobe', label: 'Aqtobe', className: 'left-pad' },
    { value: 'Asia/Ashgabat', label: 'Ashgabat', className: 'left-pad' },
    { value: 'Asia/Atyrau', label: 'Atyrau', className: 'left-pad' },
    { value: 'Asia/Baghdad', label: 'Baghdad', className: 'left-pad' },
    { value: 'Asia/Bahrain', label: 'Bahrain', className: 'left-pad' },
    { value: 'Asia/Baku', label: 'Baku', className: 'left-pad' },
    { value: 'Asia/Bangkok', label: 'Bangkok', className: 'left-pad' },
    { value: 'Asia/Barnaul', label: 'Barnaul', className: 'left-pad' },
    { value: 'Asia/Beirut', label: 'Beirut', className: 'left-pad' },
    { value: 'Asia/Bishkek', label: 'Bishkek', className: 'left-pad' },
    { value: 'Asia/Brunei', label: 'Brunei', className: 'left-pad' },
    { value: 'Asia/Chita', label: 'Chita', className: 'left-pad' },
    { value: 'Asia/Choibalsan', label: 'Choibalsan', className: 'left-pad' },
    { value: 'Asia/Colombo', label: 'Colombo', className: 'left-pad' },
    { value: 'Asia/Damascus', label: 'Damascus', className: 'left-pad' },
    { value: 'Asia/Dhaka', label: 'Dhaka', className: 'left-pad' },
    { value: 'Asia/Dili', label: 'Dili', className: 'left-pad' },
    { value: 'Asia/Dubai', label: 'Dubai', className: 'left-pad' },
    { value: 'Asia/Dushanbe', label: 'Dushanbe', className: 'left-pad' },
    { value: 'Asia/Famagusta', label: 'Famagusta', className: 'left-pad' },
    { value: 'Asia/Gaza', label: 'Gaza', className: 'left-pad' },
    { value: 'Asia/Hebron', label: 'Hebron', className: 'left-pad' },
    { value: 'Asia/Ho_Chi_Minh', label: 'Ho Chi Minh', className: 'left-pad' },
    { value: 'Asia/Hong_Kong', label: 'Hong Kong', className: 'left-pad' },
    { value: 'Asia/Hovd', label: 'Hovd', className: 'left-pad' },
    { value: 'Asia/Irkutsk', label: 'Irkutsk', className: 'left-pad' },
    { value: 'Asia/Jakarta', label: 'Jakarta', className: 'left-pad' },
    { value: 'Asia/Jayapura', label: 'Jayapura', className: 'left-pad' },
    { value: 'Asia/Jerusalem', label: 'Jerusalem', className: 'left-pad' },
    { value: 'Asia/Kabul', label: 'Kabul', className: 'left-pad' },
    { value: 'Asia/Kamchatka', label: 'Kamchatka', className: 'left-pad' },
    { value: 'Asia/Karachi', label: 'Karachi', className: 'left-pad' },
    { value: 'Asia/Kathmandu', label: 'Kathmandu', className: 'left-pad' },
    { value: 'Asia/Khandyga', label: 'Khandyga', className: 'left-pad' },
    { value: 'Asia/Kolkata', label: 'Kolkata', className: 'left-pad' },
    { value: 'Asia/Krasnoyarsk', label: 'Krasnoyarsk', className: 'left-pad' },
    { value: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur', className: 'left-pad' },
    { value: 'Asia/Kuching', label: 'Kuching', className: 'left-pad' },
    { value: 'Asia/Kuwait', label: 'Kuwait', className: 'left-pad' },
    { value: 'Asia/Macau', label: 'Macau', className: 'left-pad' },
    { value: 'Asia/Magadan', label: 'Magadan', className: 'left-pad' },
    { value: 'Asia/Makassar', label: 'Makassar', className: 'left-pad' },
    { value: 'Asia/Manila', label: 'Manila', className: 'left-pad' },
    { value: 'Asia/Muscat', label: 'Muscat', className: 'left-pad' },
    { value: 'Asia/Nicosia', label: 'Nicosia', className: 'left-pad' },
    { value: 'Asia/Novokuznetsk', label: 'Novokuznetsk', className: 'left-pad' },
    { value: 'Asia/Novosibirsk', label: 'Novosibirsk', className: 'left-pad' },
    { value: 'Asia/Omsk', label: 'Omsk', className: 'left-pad' },
    { value: 'Asia/Oral', label: 'Oral', className: 'left-pad' },
    { value: 'Asia/Phnom_Penh', label: 'Phnom Penh', className: 'left-pad' },
    { value: 'Asia/Pontianak', label: 'Pontianak', className: 'left-pad' },
    { value: 'Asia/Pyongyang', label: 'Pyongyang', className: 'left-pad' },
    { value: 'Asia/Qatar', label: 'Qatar', className: 'left-pad' },
    { value: 'Asia/Qostanay', label: 'Qostanay', className: 'left-pad' },
    { value: 'Asia/Qyzylorda', label: 'Qyzylorda', className: 'left-pad' },
    { value: 'Asia/Riyadh', label: 'Riyadh', className: 'left-pad' },
    { value: 'Asia/Sakhalin', label: 'Sakhalin', className: 'left-pad' },
    { value: 'Asia/Samarkand', label: 'Samarkand', className: 'left-pad' },
    { value: 'Asia/Seoul', label: 'Seoul', className: 'left-pad' },
    { value: 'Asia/Shanghai', label: 'Shanghai', className: 'left-pad' },
    { value: 'Asia/Singapore', label: 'Singapore', className: 'left-pad' },
    { value: 'Asia/Srednekolymsk', label: 'Srednekolymsk', className: 'left-pad' },
    { value: 'Asia/Taipei', label: 'Taipei', className: 'left-pad' },
    { value: 'Asia/Tashkent', label: 'Tashkent', className: 'left-pad' },
    { value: 'Asia/Tbilisi', label: 'Tbilisi', className: 'left-pad' },
    { value: 'Asia/Tehran', label: 'Tehran', className: 'left-pad' },
    { value: 'Asia/Thimphu', label: 'Thimphu', className: 'left-pad' },
    { value: 'Asia/Tokyo', label: 'Tokyo', className: 'left-pad' },
    { value: 'Asia/Tomsk', label: 'Tomsk', className: 'left-pad' },
    { value: 'Asia/Ulaanbaatar', label: 'Ulaanbaatar', className: 'left-pad' },
    { value: 'Asia/Urumqi', label: 'Urumqi', className: 'left-pad' },
    { value: 'Asia/Ust-Nera', label: 'Ust-Nera', className: 'left-pad' },
    { value: 'Asia/Vientiane', label: 'Vientiane', className: 'left-pad' },
    { value: 'Asia/Vladivostok', label: 'Vladivostok', className: 'left-pad' },
    { value: 'Asia/Yakutsk', label: 'Yakutsk', className: 'left-pad' },
    { value: 'Asia/Yangon', label: 'Yangon', className: 'left-pad' },
    { value: 'Asia/Yekaterinburg', label: 'Yekaterinburg', className: 'left-pad' },
    { value: 'Asia/Yerevan', label: 'Yerevan', className: 'left-pad' },
  ]
  export const Atlantic = [
    { value: 'Atlantic/Azores', label: 'Azores', className: 'left-pad' },
    { value: 'Atlantic/Bermuda', label: 'Bermuda', className: 'left-pad' },
    { value: 'Atlantic/Canary', label: 'Canary', className: 'left-pad' },
    { value: 'Atlantic/Cape_Verde', label: 'Cape Verde', className: 'left-pad' },
    { value: 'Atlantic/Faroe', label: 'Faroe', className: 'left-pad' },
    { value: 'Atlantic/Madeira', label: 'Madeira', className: 'left-pad' },
    { value: 'Atlantic/Reykjavik', label: 'Reykjavik', className: 'left-pad' },
    { value: 'Atlantic/South_Georgia', label: 'South Georgia', className: 'left-pad' },
    { value: 'Atlantic/Stanley', label: 'Stanley', className: 'left-pad' },
    { value: 'Atlantic/St_Helena', label: 'St Helena', className: 'left-pad' },
  ]
  export const Australia = [
    { value: 'Australia/Adelaide', label: 'Adelaide', className: 'left-pad' },
    { value: 'Australia/Brisbane', label: 'Brisbane', className: 'left-pad' },
    { value: 'Australia/Broken_Hill', label: 'Broken Hill', className: 'left-pad' },
    { value: 'Australia/Currie', label: 'Currie', className: 'left-pad' },
    { value: 'Australia/Darwin', label: 'Darwin', className: 'left-pad' },
    { value: 'Australia/Eucla', label: 'Eucla', className: 'left-pad' },
    { value: 'Australia/Hobart', label: 'Hobart', className: 'left-pad' },
    { value: 'Australia/Lindeman', label: 'Lindeman', className: 'left-pad' },
    { value: 'Australia/Lord_Howe', label: 'Lord Howe', className: 'left-pad' },
    { value: 'Australia/Melbourne', label: 'Melbourne', className: 'left-pad' },
    { value: 'Australia/Perth', label: 'Perth', className: 'left-pad' },
    { value: 'Australia/Sydney', label: 'Sydney', className: 'left-pad' },
  ]
  export const Europe = [
    { value: 'Europe/Amsterdam', label: 'Amsterdam', className: 'left-pad' },
    { value: 'Europe/Andorra', label: 'Andorra', className: 'left-pad' },
    { value: 'Europe/Astrakhan', label: 'Astrakhan', className: 'left-pad' },
    { value: 'Europe/Athens', label: 'Athens', className: 'left-pad' },
    { value: 'Europe/Belgrade', label: 'Belgrade', className: 'left-pad' },
    { value: 'Europe/Berlin', label: 'Berlin', className: 'left-pad' },
    { value: 'Europe/Bratislava', label: 'Bratislava', className: 'left-pad' },
    { value: 'Europe/Brussels', label: 'Brussels', className: 'left-pad' },
    { value: 'Europe/Bucharest', label: 'Bucharest', className: 'left-pad' },
    { value: 'Europe/Budapest', label: 'Budapest', className: 'left-pad' },
    { value: 'Europe/Busingen', label: 'Busingen', className: 'left-pad' },
    { value: 'Europe/Chisinau', label: 'Chisinau', className: 'left-pad' },
    { value: 'Europe/Copenhagen', label: 'Copenhagen', className: 'left-pad' },
    { value: 'Europe/Dublin', label: 'Dublin', className: 'left-pad' },
    { value: 'Europe/Gibraltar', label: 'Gibraltar', className: 'left-pad' },
    { value: 'Europe/Guernsey', label: 'Guernsey', className: 'left-pad' },
    { value: 'Europe/Helsinki', label: 'Helsinki', className: 'left-pad' },
    { value: 'Europe/Isle_of_Man', label: 'Isle of Man', className: 'left-pad' },
    { value: 'Europe/Istanbul', label: 'Istanbul', className: 'left-pad' },
    { value: 'Europe/Jersey', label: 'Jersey', className: 'left-pad' },
    { value: 'Europe/Kaliningrad', label: 'Kaliningrad', className: 'left-pad' },
    { value: 'Europe/Kiev', label: 'Kiev', className: 'left-pad' },
    { value: 'Europe/Kirov', label: 'Kirov', className: 'left-pad' },
    { value: 'Europe/Lisbon', label: 'Lisbon', className: 'left-pad' },
    { value: 'Europe/Ljubljana', label: 'Ljubljana', className: 'left-pad' },
    { value: 'Europe/London', label: 'London', className: 'left-pad' },
    { value: 'Europe/Luxembourg', label: 'Luxembourg', className: 'left-pad' },
    { value: 'Europe/Madrid', label: 'Madrid', className: 'left-pad' },
    { value: 'Europe/Malta', label: 'Malta', className: 'left-pad' },
    { value: 'Europe/Mariehamn', label: 'Mariehamn', className: 'left-pad' },
    { value: 'Europe/Minsk', label: 'Minsk', className: 'left-pad' },
    { value: 'Europe/Monaco', label: 'Monaco', className: 'left-pad' },
    { value: 'Europe/Moscow', label: 'Moscow', className: 'left-pad' },
    { value: 'Europe/Oslo', label: 'Oslo', className: 'left-pad' },
    { value: 'Europe/Paris', label: 'Paris', className: 'left-pad' },
    { value: 'Europe/Podgorica', label: 'Podgorica', className: 'left-pad' },
    { value: 'Europe/Prague', label: 'Prague', className: 'left-pad' },
    { value: 'Europe/Riga', label: 'Riga', className: 'left-pad' },
    { value: 'Europe/Rome', label: 'Rome', className: 'left-pad' },
    { value: 'Europe/Samara', label: 'Samara', className: 'left-pad' },
    { value: 'Europe/San_Marino', label: 'San Marino', className: 'left-pad' },
    { value: 'Europe/Sarajevo', label: 'Sarajevo', className: 'left-pad' },
    { value: 'Europe/Saratov', label: 'Saratov', className: 'left-pad' },
    { value: 'Europe/Simferopol', label: 'Simferopol', className: 'left-pad' },
    { value: 'Europe/Skopje', label: 'Skopje', className: 'left-pad' },
    { value: 'Europe/Sofia', label: 'Sofia', className: 'left-pad' },
    { value: 'Europe/Stockholm', label: 'Stockholm', className: 'left-pad' },
    { value: 'Europe/Tallinn', label: 'Tallinn', className: 'left-pad' },
    { value: 'Europe/Tirane', label: 'Tirane', className: 'left-pad' },
    { value: 'Europe/Ulyanovsk', label: 'Ulyanovsk', className: 'left-pad' },
    { value: 'Europe/Uzhgorod', label: 'Uzhgorod', className: 'left-pad' },
    { value: 'Europe/Vaduz', label: 'Vaduz', className: 'left-pad' },
    { value: 'Europe/Vatican', label: 'Vatican', className: 'left-pad' },
    { value: 'Europe/Vienna', label: 'Vienna', className: 'left-pad' },
    { value: 'Europe/Vilnius', label: 'Vilnius', className: 'left-pad' },
    { value: 'Europe/Volgograd', label: 'Volgograd', className: 'left-pad' },
    { value: 'Europe/Warsaw', label: 'Warsaw', className: 'left-pad' },
    { value: 'Europe/Zagreb', label: 'Zagreb', className: 'left-pad' },
    { value: 'Europe/Zaporozhye', label: 'Zaporozhye', className: 'left-pad' },
    { value: 'Europe/Zurich', label: 'Zurich', className: 'left-pad' },
  ]
  export const Indian = [
    { value: 'Indian/Antananarivo', label: 'Antananarivo', className: 'left-pad' },
    { value: 'Indian/Chagos', label: 'Chagos', className: 'left-pad' },
    { value: 'Indian/Christmas', label: 'Christmas', className: 'left-pad' },
    { value: 'Indian/Cocos', label: 'Cocos', className: 'left-pad' },
    { value: 'Indian/Comoro', label: 'Comoro', className: 'left-pad' },
    { value: 'Indian/Kerguelen', label: 'Kerguelen', className: 'left-pad' },
    { value: 'Indian/Mahe', label: 'Mahe', className: 'left-pad' },
    { value: 'Indian/Maldives', label: 'Maldives', className: 'left-pad' },
    { value: 'Indian/Mauritius', label: 'Mauritius', className: 'left-pad' },
    { value: 'Indian/Mayotte', label: 'Mayotte', className: 'left-pad' },
    { value: 'Indian/Reunion', label: 'Reunion', className: 'left-pad' },
  ]
  export const Pacific = [
    { value: 'Pacific/Apia', label: 'Apia', className: 'left-pad' },
    { value: 'Pacific/Auckland', label: 'Auckland', className: 'left-pad' },
    { value: 'Pacific/Bougainville', label: 'Bougainville', className: 'left-pad' },
    { value: 'Pacific/Chatham', label: 'Chatham', className: 'left-pad' },
    { value: 'Pacific/Chuuk', label: 'Chuuk', className: 'left-pad' },
    { value: 'Pacific/Easter', label: 'Easter', className: 'left-pad' },
    { value: 'Pacific/Efate', label: 'Efate', className: 'left-pad' },
    { value: 'Pacific/Enderbury', label: 'Enderbury', className: 'left-pad' },
    { value: 'Pacific/Fakaofo', label: 'Fakaofo', className: 'left-pad' },
    { value: 'Pacific/Fiji', label: 'Fiji', className: 'left-pad' },
    { value: 'Pacific/Funafuti', label: 'Funafuti', className: 'left-pad' },
    { value: 'Pacific/Galapagos', label: 'Galapagos', className: 'left-pad' },
    { value: 'Pacific/Gambier', label: 'Gambier', className: 'left-pad' },
    { value: 'Pacific/Guadalcanal', label: 'Guadalcanal', className: 'left-pad' },
    { value: 'Pacific/Guam', label: 'Guam', className: 'left-pad' },
    { value: 'Pacific/Honolulu', label: 'Honolulu', className: 'left-pad' },
    { value: 'Pacific/Kiritimati', label: 'Kiritimati', className: 'left-pad' },
    { value: 'Pacific/Kosrae', label: 'Kosrae', className: 'left-pad' },
    { value: 'Pacific/Kwajalein', label: 'Kwajalein', className: 'left-pad' },
    { value: 'Pacific/Majuro', label: 'Majuro', className: 'left-pad' },
    { value: 'Pacific/Marquesas', label: 'Marquesas', className: 'left-pad' },
    { value: 'Pacific/Midway', label: 'Midway', className: 'left-pad' },
    { value: 'Pacific/Nauru', label: 'Nauru', className: 'left-pad' },
    { value: 'Pacific/Niue', label: 'Niue', className: 'left-pad' },
    { value: 'Pacific/Norfolk', label: 'Norfolk', className: 'left-pad' },
    { value: 'Pacific/Noumea', label: 'Noumea', className: 'left-pad' },
    { value: 'Pacific/Pago_Pago', label: 'Pago Pago', className: 'left-pad' },
    { value: 'Pacific/Palau', label: 'Palau', className: 'left-pad' },
    { value: 'Pacific/Pitcairn', label: 'Pitcairn', className: 'left-pad' },
    { value: 'Pacific/Pohnpei', label: 'Pohnpei', className: 'left-pad' },
    { value: 'Pacific/Port_Moresby', label: 'Port Moresby', className: 'left-pad' },
    { value: 'Pacific/Rarotonga', label: 'Rarotonga', className: 'left-pad' },
    { value: 'Pacific/Saipan', label: 'Saipan', className: 'left-pad' },
    { value: 'Pacific/Tahiti', label: 'Tahiti', className: 'left-pad' },
    { value: 'Pacific/Tarawa', label: 'Tarawa', className: 'left-pad' },
    { value: 'Pacific/Tongatapu', label: 'Tongatapu', className: 'left-pad' },
    { value: 'Pacific/Wake', label: 'Wake', className: 'left-pad' },
    { value: 'Pacific/Wallis', label: 'Wallis', className: 'left-pad' },
  ]
  export const UTC = [{ value: 'UTC', label: 'UTC' }]
  export const ManualOffsets = [
    { value: 'UTC-12', label: 'UTC-12', className: 'left-pad' },
    { value: 'UTC-11.5', label: 'UTC-11:30', className: 'left-pad' },
    { value: 'UTC-11', label: 'UTC-11', className: 'left-pad' },
    { value: 'UTC-10.5', label: 'UTC-10:30', className: 'left-pad' },
    { value: 'UTC-10', label: 'UTC-10', className: 'left-pad' },
    { value: 'UTC-9.5', label: 'UTC-9:30', className: 'left-pad' },
    { value: 'UTC-9', label: 'UTC-9', className: 'left-pad' },
    { value: 'UTC-8.5', label: 'UTC-8:30', className: 'left-pad' },
    { value: 'UTC-8', label: 'UTC-8', className: 'left-pad' },
    { value: 'UTC-7.5', label: 'UTC-7:30', className: 'left-pad' },
    { value: 'UTC-7', label: 'UTC-7', className: 'left-pad' },
    { value: 'UTC-6.5', label: 'UTC-6:30', className: 'left-pad' },
    { value: 'UTC-6', label: 'UTC-6', className: 'left-pad' },
    { value: 'UTC-5.5', label: 'UTC-5:30', className: 'left-pad' },
    { value: 'UTC-5', label: 'UTC-5', className: 'left-pad' },
    { value: 'UTC-4.5', label: 'UTC-4:30', className: 'left-pad' },
    { value: 'UTC-4', label: 'UTC-4', className: 'left-pad' },
    { value: 'UTC-3.5', label: 'UTC-3:30', className: 'left-pad' },
    { value: 'UTC-3', label: 'UTC-3', className: 'left-pad' },
    { value: 'UTC-2.5', label: 'UTC-2:30', className: 'left-pad' },
    { value: 'UTC-2', label: 'UTC-2', className: 'left-pad' },
    { value: 'UTC-1.5', label: 'UTC-1:30', className: 'left-pad' },
    { value: 'UTC-1', label: 'UTC-1', className: 'left-pad' },
    { value: 'UTC-0.5', label: 'UTC-0:30', className: 'left-pad' },
    { value: 'UTC+0', label: 'UTC+0', className: 'left-pad' },
    { value: 'UTC+0.5', label: 'UTC+0:30', className: 'left-pad' },
    { value: 'UTC+1', label: 'UTC+1', className: 'left-pad' },
    { value: 'UTC+1.5', label: 'UTC+1:30', className: 'left-pad' },
    { value: 'UTC+2', label: 'UTC+2', className: 'left-pad' },
    { value: 'UTC+2.5', label: 'UTC+2:30', className: 'left-pad' },
    { value: 'UTC+3', label: 'UTC+3', className: 'left-pad' },
    { value: 'UTC+3.5', label: 'UTC+3:30', className: 'left-pad' },
    { value: 'UTC+4', label: 'UTC+4', className: 'left-pad' },
    { value: 'UTC+4.5', label: 'UTC+4:30', className: 'left-pad' },
    { value: 'UTC+5', label: 'UTC+5', className: 'left-pad' },
    { value: 'UTC+5.5', label: 'UTC+5:30', className: 'left-pad' },
    { value: 'UTC+5.75', label: 'UTC+5:45', className: 'left-pad' },
    { value: 'UTC+6', label: 'UTC+6', className: 'left-pad' },
    { value: 'UTC+6.5', label: 'UTC+6:30', className: 'left-pad' },
    { value: 'UTC+7', label: 'UTC+7', className: 'left-pad' },
    { value: 'UTC+7.5', label: 'UTC+7:30', className: 'left-pad' },
    { value: 'UTC+8', label: 'UTC+8', className: 'left-pad' },
    { value: 'UTC+8.5', label: 'UTC+8:30', className: 'left-pad' },
    { value: 'UTC+8.75', label: 'UTC+8:45', className: 'left-pad' },
    { value: 'UTC+9', label: 'UTC+9', className: 'left-pad' },
    { value: 'UTC+9.5', label: 'UTC+9:30', className: 'left-pad' },
    { value: 'UTC+10', label: 'UTC+10', className: 'left-pad' },
    { value: 'UTC+10.5', label: 'UTC+10:30', className: 'left-pad' },
    { value: 'UTC+11', label: 'UTC+11', className: 'left-pad' },
    { value: 'UTC+11.5', label: 'UTC+11:30', className: 'left-pad' },
    { value: 'UTC+12', label: 'UTC+12', className: 'left-pad' },
    { value: 'UTC+12.75', label: 'UTC+12:45', className: 'left-pad' },
    { value: 'UTC+13', label: 'UTC+13', className: 'left-pad' },
    { value: 'UTC+13.75', label: 'UTC+13:45', className: 'left-pad' },
    { value: 'UTC+14', label: 'UTC+14', className: 'left-pad' },
  ]
  
  export const groupedOptions = (t) => {
    const continents = [
      {
        label: 'Africa',
        options: Africa.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'America',
        options: America.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Antarctica',
        options: Antarctica.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Arctic',
        options: Arctic.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Asia',
        options: Asia.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Atlantic',
        options: Atlantic.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Australia',
        options: Australia.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Europe',
        options: Europe.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Indian',
        options: Indian.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Pacific',
        options: Pacific.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'UTC',
        options: UTC.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
      {
        label: 'Manual Offsets',
        options: ManualOffsets.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      },
    ]
    return continents.map((o) => ({ ...o, label: t(`timezones:continents.${o.label}`) }))
  }
  export const timezoneList = (t) => {
    const resArray = [
      ...Africa.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...America.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...Antarctica.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...Arctic.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...Asia.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...Atlantic.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...Australia.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...Europe.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...Indian.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...ManualOffsets.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...Pacific.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
      ...UTC.map((o) => ({ ...o, label: t(`timezones:zones.${o.label}`) })),
    ]
    return resArray
  }
  