name: Production Frontend Cache-Clean
on:
  workflow_dispatch:
    inputs:
      env-name:
        description: 'frontend'
        required: true
      Confirm if you're on master branch:
        description: "I am on master only"
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  AWS_REGION: eu-central-1                 # set this to your preferred AWS region, e.g. us-west-1
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Cache Invalidation
        run: | 
          aws cloudfront create-invalidation --distribution-id E1VFN1HCNZRN8D --paths "/*"

